
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-05
owner: ucsb-cs156-s25
repo_name: team02-s25-05
pull_requests: [{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-integration-test","number":122,"title":"MenuItemReview integration test","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/122"},{"author":{"id":"MDQ6VXNlcjY3NzI0NTIw","is_bot":false,"login":"austish","name":"Austin Quach"},"headRefName":"AQ-MenuItems-Integration","number":119,"title":"Integration and end to end testing complete","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/119"},{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"recommendationrequest-e2e-tests","number":110,"title":"Recommendationrequest e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/110"},{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"recommendationrequest-integrationtests","number":109,"title":"Recommendationrequest integrationtests","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/109"}]
