
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-05
owner: ucsb-cs156-s25
repo_name: team02-s25-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"vs-Articles-backend","number":74,"title":"Copied over backend files from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/74"},{"author":{"id":"MDQ6VXNlcjY3NzI0NTIw","is_bot":false,"login":"austish","name":"Austin Quach"},"headRefName":"Austin---UCSBDiningCommonsMenuItem","number":73,"title":" copied backend files, created fixtures, and created form component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/73"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-Table","number":72,"title":"Awin help request table","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/72"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-FormComponent","number":70,"title":"Awin help request form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/70"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-fixtures","number":65,"title":"Added fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team02-s25-05/pull/65"}]
